inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100

AllCops:
  TargetRubyVersion: 2.3.0
  Exclude:
  - 'bin/**/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'lib/**/*'
  - 'vendor/**/*'
  - '**/*.jbuilder'
  - '**/config.ru'
  - '**/Gemfile'
  - '**/Rakefile'