language: ruby
cache: bundler # Cache the bundler. Makes builds run faster, automatically reruns build when bundler changes
rvm:
 - 2.4.4
 install:
   - bundle install # Install needed gems
   - npm install -g stylelint postcss # Install stylelint
   - npm install # Install other stylelint requirements
