# config/app.yml for rails-settings-cached

# These are the defaults for the site settings
defaults: &defaults
  site_name: "Caravan"
  theme_color: "#58b7ff"
  city_name: "Our City"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
