# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bdee63811ee1ab0a7258c1e0e77a9bd68af1ad842e8367fd86b3aaf1df69a164b374d332d7d001b10eea2ede12606c608fef39db1f3afe2672efd8f7a68db53
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

test:
  secret_key_base: 7256961f58404a62c4e21dabe2163cdda164c38a9e35186446c87f650db0d82e32d307330d0d45d35f990ac5b30ff19aa642ca80b9cbf322ed6eb7ce2e1e2a1d
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 05dce1849a6355ddd7c82555f7eefca8fd7cbe1fb3c3ef153765ad844a6699dd15668432e5d802ef375aa8e520904240df9737aa3a6aa1cc92ed57f8ac8e0364
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

